version 1.1-8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2887,7 +2887,7 @@ fi
 
 if test -z "${BLAS_LIBS}"; then
   echo "it seems you are not using a BLAS library: using our BLAS and LAPACK routines"
-  (cd src; ln -s sblas.unused sblas.f; ln -s lsame.unused lsame.f; ln -s slapack.unused slapack.f)
+  (cd src; ln -s sblas.unused sblas.f; ln -s lsame.unused lsame.f; ln -s slapack.unused slapack.f; ln -s slamc.unused slamc.f)
 else
   LIBS="${BLAS_LIBS} ${FLIBS}"
   echo "$as_me:$LINENO: checking for scopy in ${BLAS_LIBS}" >&5
@@ -2943,7 +2943,7 @@ echo "${ECHO_T}${blas_ok}" >&6
   if test "${blas_ok}" = no; then
     { echo "$as_me:$LINENO: WARNING: could not find scopy in your BLAS library, using our BLAS and LAPACK routines" >&5
 echo "$as_me: WARNING: could not find scopy in your BLAS library, using our BLAS and LAPACK routines" >&2;}
-    (cd src; ln -s sblas.unused sblas.f; ln -s lsame.unused lsame.f; ln -s slapack.unused slapack.f)
+    (cd src; ln -s sblas.unused sblas.f; ln -s lsame.unused lsame.f; ln -s slapack.unused slapack.f; ln -s slamc.unused slamc.f)
   else
     LIBS="${LAPACK_LIBS} ${BLAS_LIBS} ${FLIBS}"
     as_ac_var=`echo "ac_cv_func_${sgesdd_func}" | $as_tr_sh`
@@ -3046,7 +3046,7 @@ fi
     if test ${NO_LIBLAPACK}; then
       { echo "$as_me:$LINENO: WARNING: could not find sgesdd: using our LAPACK routines" >&5
 echo "$as_me: WARNING: could not find sgesdd: using our LAPACK routines" >&2;}
-      (cd src; ln -s slapack.unused slapack.f)
+      (cd src; ln -s slapack.unused slapack.f; ln -s slamc.unused slamc.f)
     fi
     as_ac_var=`echo "ac_cv_func_${lsame_func}" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for ${lsame_func}" >&5
@@ -3146,8 +3146,8 @@ else
 fi
 
     if test ${NO_LSAME}; then
-      { echo "$as_me:$LINENO: WARNING: could not find LSAME in your BLAS or LAPACK library, using our copy" >&5
-echo "$as_me: WARNING: could not find LSAME in your BLAS or LAPACK library, using our copy" >&2;}
+      { echo "$as_me:$LINENO: WARNING: could not find lsame in your BLAS or LAPACK library, using our copy" >&5
+echo "$as_me: WARNING: could not find lsame in your BLAS or LAPACK library, using our copy" >&2;}
       (cd src; ln -s lsame.unused lsame.f)
     fi
   fi
